-- Run this in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text unique,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'Users can read own profile'
  ) then
    create policy "Users can read own profile"
    on public.profiles
    for select
    using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'Users can update own profile'
  ) then
    create policy "Users can update own profile"
    on public.profiles
    for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
  end if;
end $$;

alter table public.profiles
add column if not exists role text not null default 'user';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
  ) then
    alter table public.profiles
    add constraint profiles_role_check check (role in ('user', 'admin'));
  end if;
end $$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, email)
  values (new.id, new.email)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.user_spot_status (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  spot_key text not null,
  is_favorite boolean not null default false,
  is_visited boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_spot_status_unique unique (user_id, spot_key),
  constraint user_spot_status_has_flag check (is_favorite or is_visited)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_spot_status_updated_at on public.user_spot_status;

create trigger set_user_spot_status_updated_at
before update on public.user_spot_status
for each row execute procedure public.set_updated_at();

alter table public.user_spot_status enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_spot_status'
      and policyname = 'Users can read own statuses'
  ) then
    create policy "Users can read own statuses"
    on public.user_spot_status
    for select
    using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_spot_status'
      and policyname = 'Users can insert own statuses'
  ) then
    create policy "Users can insert own statuses"
    on public.user_spot_status
    for insert
    with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_spot_status'
      and policyname = 'Users can update own statuses'
  ) then
    create policy "Users can update own statuses"
    on public.user_spot_status
    for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_spot_status'
      and policyname = 'Users can delete own statuses'
  ) then
    create policy "Users can delete own statuses"
    on public.user_spot_status
    for delete
    using (auth.uid() = user_id);
  end if;
end $$;

create table if not exists public.spots (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  maps_link text not null,
  place_id text,
  lat_lng text,
  image text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.spots enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Anyone can read spots'
  ) then
    create policy "Anyone can read spots"
    on public.spots
    for select
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Admins can insert spots'
  ) then
    create policy "Admins can insert spots"
    on public.spots
    for insert
    with check (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Admins can update spots'
  ) then
    create policy "Admins can update spots"
    on public.spots
    for update
    using (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    )
    with check (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Admins can delete spots'
  ) then
    create policy "Admins can delete spots"
    on public.spots
    for delete
    using (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    );
  end if;
end $$;
