-- Add profile identity fields + profile lists with public/private visibility.

alter table public.profiles
add column if not exists display_name text;

alter table public.profiles
add column if not exists username text;

alter table public.profiles
add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_username_format_check'
  ) then
    alter table public.profiles
    add constraint profiles_username_format_check
    check (
      username is null or (
        username = lower(username)
        and char_length(username) between 3 and 30
        and username ~ '^[a-z0-9._]+$'
        and username !~ '^[._]'
        and username !~ '[._]$'
        and username !~ '[._]{2,}'
      )
    );
  end if;
end $$;

create unique index if not exists profiles_username_unique
on public.profiles (lower(username));

create table if not exists public.profile_lists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  visibility text not null check (visibility in ('public', 'private')),
  slug text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profile_lists_user_visibility_unique
on public.profile_lists (user_id, visibility);

create unique index if not exists profile_lists_user_slug_unique
on public.profile_lists (user_id, slug);

alter table public.profile_lists enable row level security;

drop trigger if exists set_profiles_updated_at on public.profiles;

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_profile_lists_updated_at on public.profile_lists;

create trigger set_profile_lists_updated_at
before update on public.profile_lists
for each row execute procedure public.set_updated_at();

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_lists'
      and policyname = 'Users can read own or public profile lists'
  ) then
    create policy "Users can read own or public profile lists"
    on public.profile_lists
    for select
    using (visibility = 'public' or auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_lists'
      and policyname = 'Users can insert own profile lists'
  ) then
    create policy "Users can insert own profile lists"
    on public.profile_lists
    for insert
    with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_lists'
      and policyname = 'Users can update own profile lists'
  ) then
    create policy "Users can update own profile lists"
    on public.profile_lists
    for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_lists'
      and policyname = 'Users can delete own profile lists'
  ) then
    create policy "Users can delete own profile lists"
    on public.profile_lists
    for delete
    using (auth.uid() = user_id);
  end if;
end $$;

create table if not exists public.profile_list_items (
  id bigint generated by default as identity primary key,
  list_id uuid not null references public.profile_lists (id) on delete cascade,
  spot_id bigint not null references public.spots (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint profile_list_items_unique unique (list_id, spot_id)
);

alter table public.profile_list_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_list_items'
      and policyname = 'Users can read visible profile list items'
  ) then
    create policy "Users can read visible profile list items"
    on public.profile_list_items
    for select
    using (
      exists (
        select 1
        from public.profile_lists pl
        where pl.id = profile_list_items.list_id
          and (pl.visibility = 'public' or pl.user_id = auth.uid())
      )
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_list_items'
      and policyname = 'Users can insert own profile list items'
  ) then
    create policy "Users can insert own profile list items"
    on public.profile_list_items
    for insert
    with check (
      exists (
        select 1
        from public.profile_lists pl
        where pl.id = profile_list_items.list_id
          and pl.user_id = auth.uid()
      )
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profile_list_items'
      and policyname = 'Users can delete own profile list items'
  ) then
    create policy "Users can delete own profile list items"
    on public.profile_list_items
    for delete
    using (
      exists (
        select 1
        from public.profile_lists pl
        where pl.id = profile_list_items.list_id
          and pl.user_id = auth.uid()
      )
    );
  end if;
end $$;

create or replace function public.toggle_profile_list_visibility(target_list_id uuid)
returns void
language plpgsql
set search_path = public
as $$
declare
  current_visibility text;
  opposite_visibility text;
  sibling_list_id uuid;
begin
  select visibility
  into current_visibility
  from public.profile_lists
  where id = target_list_id
    and user_id = auth.uid();

  if current_visibility is null then
    raise exception 'List not found or not owned by current user';
  end if;

  opposite_visibility := case
    when current_visibility = 'public' then 'private'
    else 'public'
  end;

  select id
  into sibling_list_id
  from public.profile_lists
  where user_id = auth.uid()
    and visibility = opposite_visibility
    and id <> target_list_id
  limit 1;

  if sibling_list_id is null then
    update public.profile_lists
    set visibility = opposite_visibility
    where id = target_list_id;
  else
    update public.profile_lists
    set visibility = case
      when id = target_list_id then opposite_visibility
      when id = sibling_list_id then current_visibility
      else visibility
    end
    where id in (target_list_id, sibling_list_id);
  end if;
end;
$$;

-- Keep auth bootstrap in sync for new users.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  computed_display_name text;
begin
  computed_display_name := coalesce(
    nullif(initcap(regexp_replace(split_part(coalesce(new.email, ''), '@', 1), '[._-]+', ' ', 'g')), ''),
    'NewSpots User'
  );

  insert into public.profiles (user_id, email, display_name)
  values (new.id, new.email, computed_display_name)
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = coalesce(public.profiles.display_name, excluded.display_name);

  insert into public.profile_lists (user_id, title, visibility, slug)
  values
    (new.id, format('%s''s Favorites', computed_display_name), 'public', 'favorites'),
    (new.id, format('%s''s Visited', computed_display_name), 'private', 'visited')
  on conflict (user_id, visibility) do nothing;

  return new;
end;
$$;

-- Backfill default display names when absent.
update public.profiles
set display_name = coalesce(
  nullif(display_name, ''),
  nullif(initcap(regexp_replace(split_part(coalesce(email, ''), '@', 1), '[._-]+', ' ', 'g')), ''),
  'NewSpots User'
)
where display_name is null
   or btrim(display_name) = '';

-- Ensure each user has one public and one private list for v1.
insert into public.profile_lists (user_id, title, visibility, slug)
select
  p.user_id,
  format('%s''s Favorites', coalesce(nullif(p.display_name, ''), 'NewSpots User')),
  'public',
  'favorites'
from public.profiles p
on conflict (user_id, visibility) do nothing;

insert into public.profile_lists (user_id, title, visibility, slug)
select
  p.user_id,
  format('%s''s Visited', coalesce(nullif(p.display_name, ''), 'NewSpots User')),
  'private',
  'visited'
from public.profiles p
on conflict (user_id, visibility) do nothing;

-- Backfill legacy favorites/visited into the new list model.
insert into public.profile_list_items (list_id, spot_id)
select
  pl.id,
  s.id
from public.user_spot_status uss
join public.profile_lists pl
  on pl.user_id = uss.user_id
 and pl.visibility = 'public'
join public.spots s
  on uss.spot_key = regexp_replace(
    regexp_replace(lower(s.name || '-' || s.city), '[^a-z0-9]+', '-', 'g'),
    '(^-|-$)',
    '',
    'g'
  )
where uss.is_favorite
on conflict (list_id, spot_id) do nothing;

insert into public.profile_list_items (list_id, spot_id)
select
  pl.id,
  s.id
from public.user_spot_status uss
join public.profile_lists pl
  on pl.user_id = uss.user_id
 and pl.visibility = 'private'
join public.spots s
  on uss.spot_key = regexp_replace(
    regexp_replace(lower(s.name || '-' || s.city), '[^a-z0-9]+', '-', 'g'),
    '(^-|-$)',
    '',
    'g'
  )
where uss.is_visited
on conflict (list_id, spot_id) do nothing;
