-- Add admin role and admin-managed spots table.

alter table public.profiles
add column if not exists role text not null default 'user';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
  ) then
    alter table public.profiles
    add constraint profiles_role_check check (role in ('user', 'admin'));
  end if;
end $$;

create table if not exists public.spots (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  maps_link text not null,
  lat_lng text,
  image text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.spots enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Anyone can read spots'
  ) then
    create policy "Anyone can read spots"
    on public.spots
    for select
    using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Admins can insert spots'
  ) then
    create policy "Admins can insert spots"
    on public.spots
    for insert
    with check (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Admins can update spots'
  ) then
    create policy "Admins can update spots"
    on public.spots
    for update
    using (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    )
    with check (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    );
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'spots'
      and policyname = 'Admins can delete spots'
  ) then
    create policy "Admins can delete spots"
    on public.spots
    for delete
    using (
      exists (
        select 1
        from public.profiles p
        where p.user_id = auth.uid() and p.role = 'admin'
      )
    );
  end if;
end $$;
